import numpy as np


params = dict(expe_name='',
              trial_id=0,
              env_id='EpidemicVaccination-v0',
              seed=int(np.random.randint(1e6)),
              num_train_steps=500,
              simulation_horizon=360,
              algo_id='DQN_vaccine',
              algo_params=dict(eval_and_log_every=1,
                               save_policy_every=1,
                               batch_size=32,
                               gamma=0.99,
                               layers=(64,),
                               replace_target_count=5000,
                               goal_conditioned=False,
                               lr=1e-3,
                               buffer_size=1e6,
                               epsilon_greedy=0.2,
                               n_evals_if_stochastic=30),
              model_id='heffernan_model',
              model_params=dict(stochastic=False),
              cost_id='one_cost_death_toll',
              cost_params=dict(ratio_death_to_R=0.0001),
              )
